[package]
name = "matrix_static"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
matrix-sdk = { version = "0.6.2", features = ["experimental-timeline"] }