[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
chrono = "0.4.23"
clap = { version = "4.4.18", features = ["derive"] }
handlebars = "4.3.5"
matrix-sdk = "0.7.1"
rss = "2.0.1"
serde = "1.0.148"
serde_json = "1.0.91"
tokio = "1.20.1"
